### ISSUE TITLE
NPE first time user tries to pay

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1196]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.stripe.android.PaymentSession.presentPaymentMethodSelection()' on a null object reference
       at de.tum.in.tumcampusapp.component.ui.ticket.activity.StripePaymentActivity.lambda$initViews$0(StripePaymentActivity.java:114)
       at de.tum.in.tumcampusapp.component.ui.ticket.activity.-$$Lambda$StripePaymentActivity$hvnVaRNbsCaa8e4wY_nB-RKjBjU.onClick(Unknown Source:2)
       at android.view.View.performClick(View.java:6891)
       at android.view.View$PerformClick.run(View.java:26083)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

https://console.firebase.google.com/u/0/project/tca-backend-0001/crashlytics/app/android:de.tum.in.tumcampus/issues/5bdb63bdf8b88c29632b80c9

**Comment by kordianbruck** [comment]
Alright, the logic for locking the event 4 hours before start were wrong. In addition for the missing error checks on the client side, this resulted in a broken state. This should no longer happen now with the latest merged PR #1209
