### ISSUE TITLE
App crashes, when it receives an notification

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1198]
```
java.lang.NullPointerException: Attempt to read from field 'android.os.Bundle android.app.Notification.extras' on a null object reference
        at android.app.Notification.addFieldsFromContext(Notification.java:2117)
        at android.app.Notification.addFieldsFromContext(Notification.java:2109)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:303)
        at android.app.NotificationManager.notify(NotificationManager.java:291)
        at android.app.NotificationManager.notify(NotificationManager.java:275)
        at de.tum.in.tumcampusapp.service.FcmReceiverService.postNotification(FcmReceiverService.kt:112)
        at de.tum.in.tumcampusapp.service.FcmReceiverService.onMessageReceived(FcmReceiverService.kt:79)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by kordianbruck** [comment]
Fixed in https://github.com/TUM-Dev/Campus-Android/commit/c6b895aeebb7ed44f8a05350bb00ffc1c003fc0f

I'm guessing the kotlin conversion went wrong somewhere and this condition was removed? @thellmund

**Comment by thellmund** [comment]
@kordianbruck If that were the case, this crash would have occurred before today (the conversion to Kotlin was done sometime in May).
