### ISSUE TITLE
ChatMember of a ChatMessage seems to be null

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1218]
```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter member
       at de.tum.in.tumcampusapp.database.Converters.fromMember(Unknown Source:2)
       at de.tum.in.tumcampusapp.component.ui.chat.ChatMessageDao_Impl$1.bind(ChatMessageDao_Impl.java:63)
       at de.tum.in.tumcampusapp.component.ui.chat.ChatMessageDao_Impl$1.bind(ChatMessageDao_Impl.java:36)
       at android.arch.persistence.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:63)
       at de.tum.in.tumcampusapp.component.ui.chat.ChatMessageDao_Impl.replaceMessage(ChatMessageDao_Impl.java:106)
       at de.tum.in.tumcampusapp.component.ui.chat.repository.ChatMessageLocalRepository$replaceMessage$1.run(ChatMessageLocalRepository.kt:34)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

https://console.firebase.google.com/u/0/project/tca-backend-0001/crashlytics/app/android:de.tum.in.tumcampus/issues/5bed8167f8b88c29630b9a12

Not sure how this is happening, or why... It should actually not.

**Comment by kordianbruck** [comment]
No exceptions were reported in the last seven days.
