### ISSUE TITLE
Crash when opening buy ticket activity

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1250]
```
2019-01-22 10:36:43.376 23441-23441/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tum.in.tumcampus, PID: 23441
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.tum.in.tumcampus/de.tum.in.tumcampusapp.component.ui.ticket.activity.BuyTicketActivity}: java.lang.IllegalStateException: de.tum.in.tumcampusapp.component.ui.ticket.model.EventType must be set
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3037)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: de.tum.in.tumcampusapp.component.ui.ticket.model.EventType must be set
        at de.tum.in.tumcampusapp.di.DaggerAppComponent$TicketsComponentBuilder.build(DaggerAppComponent.java:537)
        at de.tum.in.tumcampusapp.component.ui.ticket.activity.BuyTicketActivity.onCreate(BuyTicketActivity.java:76)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-01-22 10:36:43.386 23441-23493/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
```

**Comment by kordianbruck** [comment]
There is a mismatch in the order / matching of movies to tickets. Bohemian Rapsody on Thursday does not have an ticket in there.

**Comment by jacqueline8711** [comment]
This seems like it was fixed? Or is it still crashing?

**Comment by kordianbruck** [comment]
@jacqueline8711 seems to be working on latest master.
