### ISSUE TITLE
Missing Update note logs an exception

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1255]
```
2019-02-04 20:57:41.372 29240-29307/de.tum.in.tumcampus E/UpdateNoteController: java.io.EOFException: End of input at line 1 column 1 path $
    java.io.EOFException: End of input at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:207)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:39)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at de.tum.in.tumcampusapp.api.app.TUMCabeClient.getUpdateNote(TUMCabeClient.java:417)
        at de.tum.in.tumcampusapp.component.ui.updatenote.UpdateNoteController.downloadUpdateNote(UpdateNoteController.kt:16)
        at de.tum.in.tumcampusapp.service.DownloadService.downloadUpdateNote(DownloadService.kt:156)
        at de.tum.in.tumcampusapp.service.DownloadService.downloadAll(DownloadService.kt:112)
        at de.tum.in.tumcampusapp.service.DownloadService.access$downloadAll(DownloadService.kt:36)
        at de.tum.in.tumcampusapp.service.DownloadService$Companion.download(DownloadService.kt:253)
        at de.tum.in.tumcampusapp.service.DownloadService$Companion.access$download(DownloadService.kt:211)
        at de.tum.in.tumcampusapp.service.DownloadService$onHandleWork$1.invoke(DownloadService.kt:84)
        at de.tum.in.tumcampusapp.service.DownloadService$onHandleWork$1.invoke(DownloadService.kt:36)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
        at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
        at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

This should not happen. If there is no update note, simply don't display anything.

**Comment by jacqueline8711** [comment]
Fixed by https://github.com/kordianbruck/tca-backend/pull/58
