### ISSUE TITLE
Changed Studyrooms API causes SQL exception

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1256]
```
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: study_rooms.code (code 1299 SQLITE_CONSTRAINT_NOTNULL)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:80)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at de.tum.in.tumcampusapp.component.ui.studyroom.StudyRoomDao_Impl.insert(StudyRoomDao_Impl.java:85)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at de.tum.in.tumcampusapp.component.ui.studyroom.StudyRoomGroupManager$updateDatabase$1.invoke(StudyRoomGroupManager.kt:31)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at de.tum.in.tumcampusapp.component.ui.studyroom.StudyRoomGroupManager$updateDatabase$1.invoke(StudyRoomGroupManager.kt:12)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-02-04 21:04:04.306 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-02-04 21:04:04.357 29240-29295/de.tum.in.tumcampus I/chatty: uid=10283(de.tum.in.tumcampus) RenderThread identical 3 lines
2019-02-04 21:04:04.375 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-02-04 21:04:04.391 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-02-04 21:04:04.443 29240-29295/de.tum.in.tumcampus I/chatty: uid=10283(de.tum.in.tumcampus) RenderThread identical 3 lines
2019-02-04 21:04:04.464 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
```

Screen stays blank and no information is displayed.

**Comment by jacqueline8711** [comment]
@kordianbruck I cannot reproduce this. All the rooms have a code as they should have (otherwise nobody would know where the room is). 
The two StudiTUM locations are blank because there are no rooms there yet. We should probably make an indicator/placeholder for that so users aren't confused by the empty screens or just not show locations that don't have any rooms.
