### ISSUE TITLE
Logging out in dark theme causes app to crash

### ISSUE THREAD

**Issue by Liqs-v2** [TUM-Dev/Campus-Android#1418]
## Steps to Reproduce

1. Be logged in (connected to TUMOnline)
2. Open the Settings via the drawer menu
3. Scroll down and press the **"Log out"**-Button

## Expected Result
The user is logged out, the app reloads and the user sees the updated SettingsFragment without the "Log out"-Button.

## Actual Result
The user **is logged out**, but the **app crashes while reloading**. When the app is reopened manually, the user is logged out.

### Screenrecording on an emulated Android device
![dark_theme_logout_broken](https://user-images.githubusercontent.com/9247500/146401315-8c890757-3f8e-4eaa-93af-e15dcc6f36bd.gif)

## Problem
The app crashes when users with phones in **dark theme attempt to log out**.

### Stacktrace
```
2021-12-16 16:34:19.831 15990-15990/de.tum.in.tumcampus E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tum.in.tumcampus, PID: 15990
    java.lang.IllegalStateException: Fragment SettingsFragment{57a2e84} (f7f6f36a-f989-453a-abfd-57c5aae19571)} not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
        at de.tum.in.tumcampusapp.component.other.settings.SettingsFragment$themeProvider$2.invoke(SettingsFragment.kt:52)
        at de.tum.in.tumcampusapp.component.other.settings.SettingsFragment$themeProvider$2.invoke(SettingsFragment.kt:52)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at de.tum.in.tumcampusapp.component.other.settings.SettingsFragment.getThemeProvider(SettingsFragment.kt:52)
        at de.tum.in.tumcampusapp.component.other.settings.SettingsFragment.onSharedPreferenceChanged(SettingsFragment.kt:202)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
        at androidx.preference.PreferenceManager.setNoCommit(PreferenceManager.java:513)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:142)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:445)
        at de.tum.in.tumcampusapp.component.other.settings.SettingsFragment.onCreatePreferences(SettingsFragment.kt:71)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:228)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2001)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

## Suggested Enhancement :sparkles:
Make sure logging out works for any possible user specified themes, without crashing the application.

### Environment
* Phone: Samsung Galaxy S20+ and in emulated device see below
![bug_dark_theme_emulated](https://user-images.githubusercontent.com/9247500/146401444-0625bb1f-e49c-4c9e-9594-de0fa12636c4.png)

* OS version: Android
* TUM Campus App version: v3.14-dev, **Spotted in commit `1dd4b96f49f2fe4dc4ee77ab24b626f0cfa541dd`**
* Language: English

**Comment by Bentipa** [comment]
Closed via #1448
