### ISSUE TITLE
Frequent App Crashes on Android 12

### ISSUE THREAD

**Issue by ctsk** [TUM-Dev/Campus-Android#1432]
## Steps to Reproduce

1. Open App and Log into TUM Online
2. Navigate to My Lectures
3. Navigate to Chat rooms

(Lots of other navigation flows produce the same crash)

## Expected Result
See the chat rooms

## Actual Result
App crashes

## Problem
Seems connected to this issue: https://github.com/emilsjolander/StickyListHeaders/issues/477

Stack Trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.tum.in.tumcampus, PID: 20326
    java.lang.IllegalStateException: Handling non empty state of parent class is not implemented
        at se.emilsjolander.stickylistheaders.StickyListHeadersListView.onSaveInstanceState(StickyListHeadersListView.java:1098)
        at android.view.View.dispatchSaveInstanceState(View.java:20984)
        at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3975)
        at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3981)
        at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3981)
        at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3981)
        at android.view.View.saveHierarchyState(View.java:20967)
        at androidx.fragment.app.FragmentStateManager.saveViewState(FragmentStateManager.java:466)
        at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:441)
        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)
        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)
        at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2398)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:512)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)
        at android.app.Activity.performSaveInstanceState(Activity.java:2200)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1520)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5830)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5229)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5195)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5260)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

## Suggested Enhancement :sparkles:
- Some fixes were suggested in these issues:
  - https://github.com/emilsjolander/StickyListHeaders/issues/477
  - https://github.com/emilsjolander/StickyListHeaders/issues/483
 
Easiest: Switch to this fork https://github.com/mtotschnig/StickyListHeaders

### Environment
* Phone: Pixel 
* OS version:  12
* TUM Campus App version: v3.13
* Language: English

**Comment by ctsk** [comment]
Fixed by https://github.com/TUM-Dev/Campus-Android/pull/1435
